controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    
    publish_rate: 50.0

    base_frame_id: base_link

    right_wheel_names: ['right_wheel_joint']
    left_wheel_names: ['left_wheel_joint']

    wheel_separation: 0.1135
    wheel_radius: 0.0375

    use_stamped_vel: false

   